spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data?characterEncoding=utf8
    username: root
    password: root
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters,去掉后监控界面SQL将无法统计,‘wall’用于防火墙
    filters: stat,wall,log4j
server:
  port: 8080
  servlet:
    context-path: /spDruid/*
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.gree.lss.springbootDruid.model

mapper:
  mappers: com.gree.lss.springbootDruid.mapper
  not-empty: false
  identity: MYSQL

#pageHelper
pageHelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check